version: "3"
services:
  nginx:
    image: arm32v6/nginx:mainline-alpine-perl
    container_name: edge-nginx
    hostname: edge-nginx
    volumes:
      - ./wp_site:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=edge.haomo
      - NGINX_PORT=80
    links:
      - db:db
      - wordpress:wordpress
  db:
    image: biarms/mysql:5.5.60-linux-armv6l
    container_name: edge-wordpress-mysql
    hostname: edge-wordpress-mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: your-mysql-root-password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "14306:3306"
  wordpress:
    depends_on:
      - db
    image: arm32v6/wordpress:5.2.1-php7.3-fpm-alpine
    container_name: edge-wordpress
    hostname: edge-wordpress
    volumes:
      - ./wp_site:/var/www/html
    restart: always
    stdin_open: true
    tty: true
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
